param(
    [switch]$Force,
    [switch]$SkipServerInstall
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$androidProjectRoot = Join-Path $repoRoot "samples\\CameraAccessAndroid"
$iosProjectRoot = Join-Path $repoRoot "samples\\CameraAccess\\CameraAccess"
$androidSecretsPath = Join-Path $androidProjectRoot "app\\src\\main\\java\\com\\meta\\wearable\\dat\\externalsampleapps\\cameraaccess\\Secrets.kt"
$androidSecretsExamplePath = "$androidSecretsPath.example"
$iosSecretsPath = Join-Path $iosProjectRoot "Secrets.swift"
$iosSecretsExamplePath = "$iosSecretsPath.example"
$androidLocalPropertiesPath = Join-Path $androidProjectRoot "local.properties"
$serverRoot = Join-Path $repoRoot "samples\\CameraAccess\\server"

function Write-Status {
    param([string]$Message)
    Write-Host "==> $Message"
}

function Ensure-FileFromExample {
    param(
        [string]$SourcePath,
        [string]$DestinationPath
    )

    if ((Test-Path $DestinationPath) -and -not $Force) {
        Write-Status "Keeping existing $(Split-Path -Leaf $DestinationPath)"
        return
    }

    Copy-Item -LiteralPath $SourcePath -Destination $DestinationPath -Force
    Write-Status "Created $(Split-Path -Leaf $DestinationPath) from template"
}

function Find-AndroidSdkPath {
    $candidates = @(
        $env:ANDROID_SDK_ROOT,
        $env:ANDROID_HOME,
        (Join-Path $env:LOCALAPPDATA "Android\\Sdk"),
        (Join-Path $env:USERPROFILE "AppData\\Local\\Android\\Sdk")
    ) | Where-Object { $_ } | Select-Object -Unique

    foreach ($candidate in $candidates) {
        if (Test-Path $candidate) {
            return (Resolve-Path $candidate).Path
        }
    }

    return $null
}

function Read-JavaProperties {
    param([string]$Path)

    $properties = [ordered]@{}
    if (-not (Test-Path $Path)) {
        return $properties
    }

    foreach ($line in Get-Content -LiteralPath $Path) {
        if ([string]::IsNullOrWhiteSpace($line)) {
            continue
        }
        if ($line.TrimStart().StartsWith("#")) {
            continue
        }
        $parts = $line -split "=", 2
        if ($parts.Count -eq 2) {
            $properties[$parts[0].Trim()] = $parts[1]
        }
    }

    return $properties
}

function Write-LocalProperties {
    param(
        [string]$Path,
        [string]$SdkPath
    )

    $properties = Read-JavaProperties -Path $Path
    if ($SdkPath) {
        $properties["sdk.dir"] = $SdkPath.Replace("\", "/")
    }

    $lines = @(
        "# Auto-generated by scripts/setup-local.ps1"
        "# Android Studio can update this file as needed."
    )

    foreach ($entry in $properties.GetEnumerator()) {
        $lines += "$($entry.Key)=$($entry.Value)"
    }

    if (-not $properties.Contains("github_token")) {
        $lines += "# Optional: GitHub personal access token with read:packages scope."
        $lines += "# github_token=ghp_your_token_here"
    }

    Set-Content -LiteralPath $Path -Value $lines
    Write-Status "Wrote local.properties"
}

Ensure-FileFromExample -SourcePath $androidSecretsExamplePath -DestinationPath $androidSecretsPath
Ensure-FileFromExample -SourcePath $iosSecretsExamplePath -DestinationPath $iosSecretsPath

$androidSdkPath = Find-AndroidSdkPath
if ($androidSdkPath) {
    Write-LocalProperties -Path $androidLocalPropertiesPath -SdkPath $androidSdkPath
} else {
    Write-Status "Android SDK not found automatically. Skipping local.properties generation."
}

if (-not $SkipServerInstall) {
    if (Get-Command npm -ErrorAction SilentlyContinue) {
        Write-Status "Installing signaling server dependencies"
        npm install --prefix $serverRoot
    } else {
        Write-Status "npm is not installed. Skipping server dependency install."
    }
}

Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Add your Gemini API key in samples/CameraAccess/CameraAccess/Secrets.swift or the app settings."
Write-Host "  2. Add a GitHub Packages token to samples/CameraAccessAndroid/local.properties or set GITHUB_TOKEN."
Write-Host "  3. Open samples/CameraAccessAndroid in Android Studio to start working on Android."
Write-Host "  4. Use samples/CameraAccess on a Mac if you want to work on the iOS app."
